version: "2"
run:
  modules-download-mode: mod
  issues-exit-code: 1
  tests: true
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - decorder
    - durationcheck
    - errcheck
    - errorlint
    - gocritic
    - gocyclo
    - goheader
    - gomodguard
    - govet
    - ineffassign
    - lll
    - makezero
    - misspell
    - nilerr
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - thelper
    - unused
    - wastedassign
  settings:
    gocyclo:
      min-complexity: 50
    govet:
      enable-all: true
      settings:
        shadow:
          strict: true
    lll:
      line-length: 180
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: Error return value of `.*.Unlock` is not checked
      - path: (.+)\.go$
        text: Error return value of `.*.Completed` is not checked
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 1000
  max-same-issues: 100
  uniq-by-line: true
formatters:
  enable:
    - gofumpt
    - goimports
    - gci
    - golines
  settings:
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/scylladb/scylla-bench
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/scylladb/scylla-bench)
        - prefix(github.com/scylladb/gocql)
    golines:
      max-len: 180
      shorten-comments: true
