version: 2

report_sizes: true

builds:
  - id: scylla-bench
    goos:
      - linux
    binary: scylla-bench
    no_unique_dist_dir: false
    env:
      - CGO_ENABLED=0
      - CFLAGS="-O3"
      - CXXFLAGS="-O3"
    goarch:
      - amd64
      - arm64
    main: .
    ldflags:
      - -s -w
      - -X github.com/scylladb/scylla-bench/internal/version.version={{.Version}}
      - -X github.com/scylladb/scylla-bench/internal/version.commit={{.Commit}}
      - -X github.com/scylladb/scylla-bench/internal/version.date={{.Date}}
      - -X github.com/scylladb/scylla-bench/internal/version.driverVersion={{.Env.DRIVER_VERSION}}
      - -X github.com/scylladb/scylla-bench/internal/version.driverCommit={{.Env.DRIVER_COMMIT}}
      - -X github.com/scylladb/scylla-bench/internal/version.driverDate={{.Env.DRIVER_DATE}}

archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - README.md

source:
  enabled: true
  format: 'tar.gz'

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: '{{ .Tag }}-next'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  - image_templates:
      - scylladb/scylla-bench:{{ .Version }}-amd64
    goarch: amd64
    goos: linux
    id: scylla-bench-amd64
    build_flag_templates:
      - '--platform=linux/amd64'
      - '--target=goreleaser-production'

  - image_templates:
      - scylladb/scylla-bench:{{ .Version }}-arm64v8
    goarch: arm64
    id: scylla-bench-arm
    goos: linux
    build_flag_templates:
      - '--platform=linux/arm64/v8'
      - '--target=goreleaser-production'

docker_manifests:
  - name_template: 'scylladb/scylla-bench:{{ .Version }}'
    skip_push: false
    image_templates:
      - 'scylladb/scylla-bench:{{ .Version }}-amd64'
      - 'scylladb/scylla-bench:{{ .Version }}-arm64v8'

  - name_template: 'scylladb/scylla-bench:latest'
    skip_push: false
    image_templates:
      - 'scylladb/scylla-bench:{{ .Version }}-amd64'
      - 'scylladb/scylla-bench:{{ .Version }}-arm64v8'

release:
  mode: keep-existing
  make_latest: true
  prerelease: auto
  skip_upload: false
  include_meta: true
