name: Update Docker Hub Description
on:
  push:
    branches:
      - master
    paths:
      - README.md
      - .github/workflows/dockerhub-description.yml
jobs:
  update-dockerhub-description:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v5
    - name: Update Docker Hub Description for scylladb/scylla-bench
      uses: peter-evans/dockerhub-description@v5
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password:  ${{ secrets.DOCKERHUB_TOKEN }}
        repository: scylladb/scylla-bench
        short-description: ${{ github.event.repository.description }}
        enable-url-completion: true
